# Generated by Django 5.0.14 on 2025-08-22 07:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("admin_app", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ExamHall",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="اسم القاعة كما هو معروف في الجامعة",
                        max_length=100,
                        verbose_name="اسم القاعة",
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        help_text="مثال: الدور الأول - مبنى كلية الهندسة",
                        max_length=200,
                        verbose_name="موقع القاعة",
                    ),
                ),
                (
                    "capacity",
                    models.PositiveIntegerField(
                        help_text="عدد الطلاب الذين تستوعبهم القاعة",
                        verbose_name="سعة القاعة",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="أي معلومات إضافية عن القاعة",
                        null=True,
                        verbose_name="ملاحظات",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="هل هذه القاعة متاحة للاستخدام حالياً؟",
                        verbose_name="نشطة",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
            ],
            options={
                "verbose_name": "قاعة امتحان",
                "verbose_name_plural": "قاعات الامتحانات",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="StudentExamAttendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "attendance_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الحضور"
                    ),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[(0, "أول مرة"), (1, "إعادة")],
                        default=0,
                        verbose_name="حالة الحضور",
                    ),
                ),
                (
                    "score",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="الدرجة"
                    ),
                ),
            ],
            options={
                "verbose_name": "حضور طالب للامتحان",
                "verbose_name_plural": "حضور الطلاب للامتحانات",
            },
        ),
        migrations.CreateModel(
            name="ExamSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("exam_date", models.DateField(verbose_name="تاريخ الامتحان")),
                ("start_time", models.TimeField(verbose_name="وقت بدء الامتحان")),
                ("end_time", models.TimeField(verbose_name="وقت انتهاء الامتحان")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "course",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exam_schedule",
                        to="admin_app.course",
                        verbose_name="المقرر الدراسي",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_exam_schedules",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="أنشئ بواسطة",
                    ),
                ),
                (
                    "hall",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="scheduled_exams",
                        to="conttroll_app.examhall",
                        verbose_name="قاعة الامتحان",
                    ),
                ),
            ],
            options={
                "verbose_name": "جدول الامتحانات",
                "verbose_name_plural": "الجداول الزمنية للامتحانات",
                "ordering": ["exam_date", "start_time"],
            },
        ),
        migrations.CreateModel(
            name="ExamStatusLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[
                            (1, "منشئ"),
                            (2, "مرسل للكنترول"),
                            (3, "مستلم من الكنترول"),
                            (4, "ملغي"),
                        ],
                        verbose_name="الحالة",
                    ),
                ),
                (
                    "change_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ التغيير"
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="ملاحظات"),
                ),
                (
                    "changed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="exam_status_changes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="تم التغيير بواسطة",
                    ),
                ),
            ],
            options={
                "verbose_name": "سجل حالة الامتحان",
                "verbose_name_plural": "سجلات حالات الامتحانات",
                "ordering": ["-change_date"],
            },
        ),
    ]
