# Generated by Django 5.0.14 on 2025-08-10 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ExamHall",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="اسم القاعة كما هو معروف في الجامعة",
                        max_length=100,
                        verbose_name="اسم القاعة",
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        help_text="مثال: الدور الأول - مبنى كلية الهندسة",
                        max_length=200,
                        verbose_name="موقع القاعة",
                    ),
                ),
                (
                    "capacity",
                    models.PositiveIntegerField(
                        help_text="عدد الطلاب الذين تستوعبهم القاعة",
                        verbose_name="سعة القاعة",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="أي معلومات إضافية عن القاعة",
                        null=True,
                        verbose_name="ملاحظات",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="هل هذه القاعة متاحة للاستخدام حالياً؟",
                        verbose_name="نشطة",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
            ],
            options={
                "verbose_name": "قاعة امتحان",
                "verbose_name_plural": "قاعات الامتحانات",
                "ordering": ["name"],
            },
        ),
    ]
