# Generated by Django 5.2.5 on 2025-09-05 14:51

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("admin_app", "0002_initial"),
        ("authentcat_app", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ExamScheduleView",
            fields=[
                ("id", models.BigIntegerField(primary_key=True, serialize=False)),
                ("course_id", models.BigIntegerField()),
                ("course_name", models.CharField(max_length=100)),
                ("course_type", models.CharField(max_length=50)),
                ("exam_id", models.BigIntegerField()),
                ("exam_name", models.CharField(max_length=255)),
                ("exam_type", models.CharField(max_length=50)),
                ("exam_status", models.IntegerField(blank=True, null=True)),
                ("department_id", models.BigIntegerField()),
                ("department_name", models.CharField(max_length=100)),
                ("major_id", models.BigIntegerField()),
                ("major_name", models.CharField(max_length=100)),
                ("level_id", models.BigIntegerField()),
                ("level_name", models.CharField(max_length=50)),
                ("semester_id", models.BigIntegerField()),
                ("semester_name", models.CharField(max_length=100)),
                ("hall_id", models.BigIntegerField()),
                ("hall_name", models.CharField(max_length=100)),
                ("exam_date", models.DateField()),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
            ],
            options={
                "db_table": "ExamScheduleView",
                "ordering": [
                    "department_name",
                    "major_name",
                    "level_name",
                    "semester_name",
                    "exam_date",
                    "start_time",
                    "course_name",
                ],
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Acdimaic_and_term_from_uivercity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "Acdimaic_year",
                    models.CharField(max_length=10, verbose_name="السنة الدراسية"),
                ),
                (
                    "Acdimaic_year_semester",
                    models.CharField(max_length=10, verbose_name="فصل السنة الدراسية"),
                ),
            ],
            options={
                "verbose_name": "الفصل و الترم من تقرير الجامعة",
                "verbose_name_plural": "الفصل و الترم من تقرير الجامعة",
            },
        ),
        migrations.CreateModel(
            name="ExamHall",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="اسم القاعة كما هو معروف في الجامعة",
                        max_length=100,
                        verbose_name="اسم القاعة",
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        help_text="مثال: الدور الأول - مبنى كلية الهندسة",
                        max_length=200,
                        verbose_name="موقع القاعة",
                    ),
                ),
                (
                    "capacity",
                    models.PositiveIntegerField(
                        help_text="عدد الطلاب الذين تستوعبهم القاعة",
                        verbose_name="سعة القاعة",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="أي معلومات إضافية عن القاعة",
                        null=True,
                        verbose_name="ملاحظات",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="هل هذه القاعة متاحة للاستخدام حالياً؟",
                        verbose_name="نشطة",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
            ],
            options={
                "verbose_name": "قاعة امتحان",
                "verbose_name_plural": "قاعات الامتحانات",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="student_courses_grads",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "midterm_mark",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=6,
                        verbose_name="درجة الامتحان النصفي",
                    ),
                ),
                (
                    "final_mark",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=6,
                        verbose_name="درجة الامتحان النهائي",
                    ),
                ),
                (
                    "classwork_mark",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=6,
                        verbose_name="درجة الامتحان أعمال الفصل",
                    ),
                ),
                (
                    "total_mark",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=6,
                        verbose_name="المجموع",
                    ),
                ),
            ],
            options={
                "verbose_name": "درجات الطلاب في المقررات",
                "verbose_name_plural": "درجات الطلاب في المقررات",
            },
        ),
        migrations.CreateModel(
            name="student_report_from_uivercity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=70, verbose_name="الاسم")),
                ("gender", models.CharField(max_length=10, verbose_name="النوع")),
                (
                    "univercity_number",
                    models.PositiveIntegerField(verbose_name="الرقم الجامعي"),
                ),
                ("major", models.CharField(max_length=30, verbose_name="التخصص")),
                (
                    "semester_id",
                    models.PositiveSmallIntegerField(verbose_name="الفصل الدراسي"),
                ),
            ],
            options={
                "verbose_name": "بيانات الطلاب من التقرير الجامعة",
                "verbose_name_plural": "بيانات الطلاب من التقرير الجامعة",
            },
        ),
        migrations.CreateModel(
            name="StudentExamAttendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "attendance_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الحضور"
                    ),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[(0, "أول مرة"), (1, "إعادة")],
                        default=0,
                        verbose_name="حالة الحضور",
                    ),
                ),
                (
                    "score",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="الدرجة"
                    ),
                ),
            ],
            options={
                "verbose_name": "حضور طالب للامتحان",
                "verbose_name_plural": "حضور الطلاب للامتحانات",
            },
        ),
        migrations.CreateModel(
            name="ExamSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("exam_date", models.DateField(verbose_name="تاريخ الامتحان")),
                ("start_time", models.TimeField(verbose_name="وقت بدء الامتحان")),
                ("end_time", models.TimeField(verbose_name="وقت انتهاء الامتحان")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "course",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exam_schedule",
                        to="admin_app.course",
                        verbose_name="المقرر الدراسي",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_exam_schedules",
                        to="authentcat_app.controlcommitteemember",
                        verbose_name="أنشئ بواسطة",
                    ),
                ),
                (
                    "hall",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="scheduled_exams",
                        to="conttroll_app.examhall",
                        verbose_name="قاعة الامتحان",
                    ),
                ),
            ],
            options={
                "verbose_name": "جدول الامتحانات",
                "verbose_name_plural": "الجداول الزمنية للامتحانات",
                "ordering": ["exam_date", "start_time"],
            },
        ),
        migrations.CreateModel(
            name="ExamStatusLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[
                            (1, "منشئ"),
                            (2, "مرسل للكنترول"),
                            (3, "مستلم من الكنترول"),
                            (4, "ملغي"),
                        ],
                        verbose_name="الحالة",
                    ),
                ),
                (
                    "change_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ التغيير"
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="ملاحظات"),
                ),
                (
                    "changed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="exam_status_changes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="تم التغيير بواسطة",
                    ),
                ),
            ],
            options={
                "verbose_name": "سجل حالة الامتحان",
                "verbose_name_plural": "سجلات حالات الامتحانات",
                "ordering": ["-change_date"],
            },
        ),
    ]
