# Generated by Django 5.0.14 on 2025-08-22 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("authentcat_app", "0001_initial"),
        ("conttroll_app", "0001_initial"),
        ("taecher_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="examstatuslog",
            name="exam",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="status_logs",
                to="taecher_app.exam",
                verbose_name="الامتحان",
            ),
        ),
        migrations.AddField(
            model_name="studentexamattendance",
            name="exam",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="student_attendances",
                to="taecher_app.exam",
                verbose_name="الامتحان",
            ),
        ),
        migrations.AddField(
            model_name="studentexamattendance",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="exam_attendances",
                to="authentcat_app.student",
                verbose_name="الطالب",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="examschedule",
            unique_together={("course",), ("hall", "exam_date", "start_time")},
        ),
        migrations.AlterUniqueTogether(
            name="studentexamattendance",
            unique_together={("student", "exam")},
        ),
    ]
