# Generated by Django 5.0.14 on 2025-08-10 13:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_app", "0006_alter_coursestructure_class_work_max_and_more"),
        ("conttroll_app", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ExamSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("exam_date", models.DateField(verbose_name="تاريخ الامتحان")),
                ("start_time", models.TimeField(verbose_name="وقت بدء الامتحان")),
                ("end_time", models.TimeField(verbose_name="وقت انتهاء الامتحان")),
                (
                    "is_published",
                    models.BooleanField(default=False, verbose_name="منشور للطلاب"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "course",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exam_schedule",
                        to="admin_app.course",
                        verbose_name="المقرر الدراسي",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_exam_schedules",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="أنشئ بواسطة",
                    ),
                ),
            ],
            options={
                "verbose_name": "جدول الامتحانات",
                "verbose_name_plural": "الجداول الزمنية للامتحانات",
                "ordering": ["exam_date", "start_time"],
            },
        ),
    ]
