# Generated by Django 5.2.5 on 2025-09-05 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("admin_app", "0002_initial"),
        ("conttroll_app", "0001_initial"),
        ("taecher_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="examstatuslog",
            name="exam",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="status_logs",
                to="taecher_app.exam",
                verbose_name="الامتحان",
            ),
        ),
        migrations.AddField(
            model_name="student_courses_grads",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="course_grads",
                to="admin_app.course",
                verbose_name="المقرر",
            ),
        ),
        migrations.AddField(
            model_name="student_courses_grads",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="student_grads",
                to="conttroll_app.student_report_from_uivercity",
                verbose_name="الطالب",
            ),
        ),
        migrations.AddField(
            model_name="studentexamattendance",
            name="exam",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="student_attendances",
                to="taecher_app.exam",
                verbose_name="الامتحان",
            ),
        ),
        migrations.AddField(
            model_name="studentexamattendance",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="exam_attendances",
                to="conttroll_app.student_report_from_uivercity",
                verbose_name="الطالب",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="examschedule",
            unique_together={("course",), ("hall", "exam_date", "start_time")},
        ),
        migrations.AlterUniqueTogether(
            name="studentexamattendance",
            unique_together={("student", "exam")},
        ),
    ]
