# Generated by Django 5.0.14 on 2025-08-22 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_app", "0003_remove_coursestructure_structure_and_more"),
        ("authentcat_app", "0001_initial"),
        ("conttroll_app", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CourseEnrollment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "enrollment_date",
                    models.DateField(auto_now_add=True, verbose_name="تاريخ التسجيل"),
                ),
                (
                    "is_repeat",
                    models.BooleanField(default=False, verbose_name="إعادة تسجيل"),
                ),
                (
                    "grade",
                    models.CharField(
                        blank=True, max_length=2, null=True, verbose_name="الدرجة"
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrollments",
                        to="admin_app.course",
                        verbose_name="المقرر",
                    ),
                ),
                (
                    "semester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrollments",
                        to="admin_app.semester",
                        verbose_name="الفصل الدراسي",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrollments",
                        to="authentcat_app.student",
                        verbose_name="الطالب",
                    ),
                ),
            ],
            options={
                "verbose_name": "تسجيل مقرر",
                "verbose_name_plural": "تسجيلات المقررات",
                "ordering": ["-enrollment_date"],
            },
        ),
        migrations.AddConstraint(
            model_name="courseenrollment",
            constraint=models.UniqueConstraint(
                fields=("student", "course", "semester"), name="unique_enrollment"
            ),
        ),
    ]
