# Generated by Django 5.2.5 on 2025-09-05 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("conttroll_app", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="examscheduleview",
            table="View_ExamSchedule",
        ),
    ]
