# Generated by Django 5.0.14 on 2025-08-10 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conttroll_app", "0002_examschedule"),
        ("taecher_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="examschedule",
            name="exam",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="schedules",
                to="taecher_app.exam",
                verbose_name="الامتحان",
            ),
        ),
        migrations.AddField(
            model_name="examschedule",
            name="hall",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="scheduled_exams",
                to="conttroll_app.examhall",
                verbose_name="قاعة الامتحان",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="examschedule",
            unique_together={("course", "exam"), ("hall", "exam_date", "start_time")},
        ),
    ]
