# Generated by Django 5.0.14 on 2025-08-22 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_app", "0004_academicyear"),
        ("authentcat_app", "0001_initial"),
        ("conttroll_app", "0003_courseenrollment_courseenrollment_unique_enrollment"),
        ("taecher_app", "0002_coursestructure"),
    ]

    operations = [
        migrations.CreateModel(
            name="Grade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("marks_obtained", models.DecimalField(decimal_places=2, max_digits=5)),
                ("total_marks", models.DecimalField(decimal_places=2, max_digits=5)),
                ("grade", models.CharField(blank=True, max_length=5, null=True)),
                (
                    "academic_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grades",
                        to="admin_app.academicyear",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grades",
                        to="admin_app.course",
                    ),
                ),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grades",
                        to="taecher_app.exam",
                    ),
                ),
                (
                    "semester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grades",
                        to="admin_app.semester",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grades",
                        to="authentcat_app.student",
                    ),
                ),
            ],
            options={
                "verbose_name": "الدرجة",
                "verbose_name_plural": "الدرجات",
                "unique_together": {("student", "course", "academic_year", "exam")},
            },
        ),
    ]
