# Generated by Django 5.0.14 on 2025-08-11 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("admin_app", "0006_alter_coursestructure_class_work_max_and_more"),
        ("conttroll_app", "0003_examschedule_exam_examschedule_hall_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="examschedule",
            unique_together={("course",), ("hall", "exam_date", "start_time")},
        ),
        migrations.RemoveField(
            model_name="examschedule",
            name="exam",
        ),
    ]
