# Generated by Django 5.0.14 on 2025-08-26 05:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentcat_app", "0001_initial"),
        ("conttroll_app", "0004_grade"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExamScheduleView",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("course_id", models.IntegerField()),
                ("course_name", models.CharField(max_length=100)),
                ("course_type", models.CharField(max_length=50)),
                ("exam_id", models.IntegerField()),
                ("exam_name", models.CharField(max_length=255)),
                ("exam_type", models.CharField(max_length=50)),
                ("exam_status", models.IntegerField(blank=True, null=True)),
                ("major_id", models.IntegerField()),
                ("major_name", models.CharField(max_length=100)),
                ("level_id", models.IntegerField()),
                ("level_name", models.CharField(max_length=50)),
                ("semester_id", models.IntegerField()),
                ("semester_name", models.CharField(max_length=50)),
                ("hall_id", models.IntegerField()),
                ("hall_name", models.CharField(max_length=100)),
                ("exam_date", models.DateField()),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
            ],
            options={
                "db_table": "ems_view_exam_schedule",
                "managed": False,
            },
        ),
        migrations.AlterField(
            model_name="examschedule",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_exam_schedules",
                to="authentcat_app.controlcommitteemember",
                verbose_name="أنشئ بواسطة",
            ),
        ),
    ]
