# Generated by Django 5.0.14 on 2025-08-11 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("conttroll_app", "0004_alter_examschedule_unique_together_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="examschedule",
            name="is_published",
        ),
    ]
