# Generated by Django 5.0.14 on 2025-08-12 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conttroll_app", "0005_remove_examschedule_is_published"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExamScheduleView",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("course_ID", models.IntegerField()),
                ("المقرر", models.CharField(max_length=100)),
                ("نوع_المقرر", models.CharField(max_length=50)),
                ("exam_id", models.IntegerField()),
                ("الامتحان", models.CharField(max_length=255)),
                ("نوع_الامتحان", models.CharField(max_length=50)),
                ("حالة_الامتحان", models.IntegerField(blank=True, null=True)),
                ("major_id", models.IntegerField()),
                ("التخصص", models.CharField(max_length=100)),
                ("level_id", models.IntegerField()),
                ("المستوي", models.CharField(max_length=50)),
                ("semsterID", models.IntegerField()),
                ("الفصل_الدراسي", models.CharField(max_length=50)),
                ("hall_id", models.IntegerField()),
                ("القاعة", models.CharField(max_length=100)),
                ("exam_date", models.DateField()),
                ("exam_open_time", models.TimeField()),
                ("exam_close_time", models.TimeField()),
            ],
            options={
                "db_table": "ems_View_Exam_Schedule",
                "managed": False,
            },
        ),
    ]
