# Generated by Django 5.0.14 on 2025-08-16 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("conttroll_app", "0006_examscheduleview"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="examscheduleview",
            table="ems_view_exam_schedule",
        ),
    ]
