# Generated by Django 5.2.5 on 2025-09-05 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CourseCatalog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="اسم المقرر")),
                (
                    "code",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="كود المقرر"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="وصف المقرر"),
                ),
                (
                    "course_type",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "نظري"), (2, "عملي")], verbose_name="نوع المقرر"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        choices=[(True, "فعال"), (False, "غير فعال")], default=True
                    ),
                ),
            ],
            options={
                "verbose_name": "مقرر (كتالوج)",
                "verbose_name_plural": "المقررات (كتالوج)",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="اسم القسم"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="كود القسم"
                    ),
                ),
            ],
            options={
                "verbose_name": "قسم",
                "verbose_name_plural": "الأقسام",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Level",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="اسم المستوى"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="كود المستوى"
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(
                        unique=True, verbose_name="ترتيب المستوى"
                    ),
                ),
            ],
            options={
                "verbose_name": "مستوى",
                "verbose_name_plural": "المستويات",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "coursecatalog_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="admin_app.coursecatalog",
                    ),
                ),
            ],
            options={
                "verbose_name": "مقرر",
                "verbose_name_plural": "المقررات",
                "ordering": ["semester"],
            },
            bases=("admin_app.coursecatalog",),
        ),
        migrations.CreateModel(
            name="Major",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="اسم التخصص"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="كود التخصص"
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="majors",
                        to="admin_app.department",
                        verbose_name="القسم",
                    ),
                ),
            ],
            options={
                "verbose_name": "تخصص",
                "verbose_name_plural": "التخصصات",
                "ordering": ["department__name", "name"],
            },
        ),
        migrations.CreateModel(
            name="Semester",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="اسم الفصل"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="كود الفصل"
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(
                        unique=True, verbose_name="ترتيب الفصول الدراسية"
                    ),
                ),
                (
                    "level",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="semester",
                        to="admin_app.level",
                        verbose_name="المستوى",
                    ),
                ),
            ],
            options={
                "verbose_name": "فصل دراسي",
                "verbose_name_plural": "الفصول الدراسية",
                "ordering": ["order"],
            },
        ),
    ]
