# Generated by Django 5.0.14 on 2025-08-09 11:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Batch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="اسم الدفعة")),
                (
                    "enrollment_year",
                    models.PositiveIntegerField(
                        editable=False, verbose_name="سنة القيد"
                    ),
                ),
            ],
            options={
                "verbose_name": "دفعة",
                "verbose_name_plural": "الدفعات",
                "ordering": ["-enrollment_year", "major__name"],
            },
        ),
        migrations.CreateModel(
            name="CourseEnrollment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "enrollment_date",
                    models.DateField(auto_now_add=True, verbose_name="تاريخ التسجيل"),
                ),
                (
                    "is_repeat",
                    models.BooleanField(default=False, verbose_name="إعادة تسجيل"),
                ),
                (
                    "grade",
                    models.CharField(
                        blank=True, max_length=2, null=True, verbose_name="الدرجة"
                    ),
                ),
            ],
            options={
                "verbose_name": "تسجيل مقرر",
                "verbose_name_plural": "تسجيلات المقررات",
                "ordering": ["-enrollment_date"],
            },
        ),
        migrations.CreateModel(
            name="CourseStructure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "final_exam_max",
                    models.PositiveIntegerField(
                        verbose_name="الدرجة العظمى للامتحان النهائي"
                    ),
                ),
                (
                    "midterm_exam_max",
                    models.PositiveIntegerField(
                        default=0, verbose_name="الدرجة العظمى للامتحان النصفي"
                    ),
                ),
                (
                    "class_work_max",
                    models.PositiveIntegerField(
                        default=0, verbose_name="الدرجة العظمى لأعمال الفصل"
                    ),
                ),
            ],
            options={
                "verbose_name": "هيكل المقرر",
                "verbose_name_plural": "هياكل المقررات",
            },
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="اسم القسم"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="كود القسم"
                    ),
                ),
            ],
            options={
                "verbose_name": "قسم",
                "verbose_name_plural": "الأقسام",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Level",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="اسم المستوى"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="كود المستوى"
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(
                        unique=True, verbose_name="ترتيب المستوى"
                    ),
                ),
            ],
            options={
                "verbose_name": "مستوى",
                "verbose_name_plural": "المستويات",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Major",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="اسم التخصص"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="كود التخصص"
                    ),
                ),
            ],
            options={
                "verbose_name": "تخصص",
                "verbose_name_plural": "التخصصات",
                "ordering": ["department__name", "name"],
            },
        ),
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="اسم المقرر")),
                (
                    "code",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="كود المقرر"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        choices=[(True, "فعال"), (False, "غير فعال")], default=True
                    ),
                ),
                (
                    "course_type",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "نظري"), (2, "عملي"), (3, "نظري/عملي")]
                    ),
                ),
                (
                    "instructor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="courses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "prerequisites",
                    models.ManyToManyField(blank=True, to="admin_app.course"),
                ),
            ],
            options={
                "verbose_name": "مقرر",
                "verbose_name_plural": "المقررات",
                "ordering": ["major__name", "code"],
            },
        ),
    ]
