# Generated by Django 5.2.5 on 2025-09-05 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("admin_app", "0001_initial"),
        ("authentcat_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="instructor",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="courses",
                to="authentcat_app.teacher",
                verbose_name="المعلم",
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="major",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="courses",
                to="admin_app.major",
                verbose_name="التخصص",
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="semester",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="courses",
                to="admin_app.semester",
                verbose_name="الفصل الدراسي",
            ),
        ),
        migrations.AddConstraint(
            model_name="major",
            constraint=models.UniqueConstraint(
                fields=("name", "department"), name="unique_major_per_department"
            ),
        ),
    ]
