# Generated by Django 5.0.14 on 2025-08-22 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("admin_app", "0001_initial"),
        ("authentcat_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="instructor",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="courses",
                to="authentcat_app.teacher",
                verbose_name="المعلم",
            ),
        ),
        migrations.AddField(
            model_name="courseenrollment",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="enrollments",
                to="admin_app.course",
                verbose_name="المقرر",
            ),
        ),
        migrations.AddField(
            model_name="courseenrollment",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="enrollments",
                to="authentcat_app.student",
                verbose_name="الطالب",
            ),
        ),
        migrations.AddField(
            model_name="coursestructure",
            name="structure",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="course",
                to="admin_app.course",
            ),
        ),
        migrations.AddField(
            model_name="major",
            name="department",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="majors",
                to="admin_app.department",
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="major",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="courses",
                to="admin_app.major",
            ),
        ),
        migrations.AddField(
            model_name="batch",
            name="major",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="التخصص",
                to="admin_app.major",
            ),
        ),
        migrations.AddField(
            model_name="semester",
            name="level",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="semester",
                to="admin_app.level",
                verbose_name="المستوى",
            ),
        ),
        migrations.AddField(
            model_name="courseenrollment",
            name="semester",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="enrollments",
                to="admin_app.semester",
                verbose_name="الفصل الدراسي",
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="semester",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="courses",
                to="admin_app.semester",
                verbose_name="الفصل الدراسي",
            ),
        ),
        migrations.AddConstraint(
            model_name="major",
            constraint=models.UniqueConstraint(
                fields=("name", "department"), name="unique_major_per_department"
            ),
        ),
        migrations.AddConstraint(
            model_name="batch",
            constraint=models.UniqueConstraint(
                fields=("name", "major"), name="unique_batch_per_major"
            ),
        ),
        migrations.AddConstraint(
            model_name="batch",
            constraint=models.UniqueConstraint(
                fields=("major", "order"), name="unique_order_per_major"
            ),
        ),
        migrations.AddConstraint(
            model_name="courseenrollment",
            constraint=models.UniqueConstraint(
                fields=("student", "course", "semester"), name="unique_enrollment"
            ),
        ),
        migrations.AddConstraint(
            model_name="course",
            constraint=models.UniqueConstraint(
                fields=("name", "major"), name="unique_course_name_per_major"
            ),
        ),
    ]
