# Generated by Django 5.0.14 on 2025-08-09 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_app", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="batch",
            options={
                "ordering": ["order", "-enrollment_year", "major__name"],
                "verbose_name": "دفعة",
                "verbose_name_plural": "الدفعات",
            },
        ),
        migrations.AddField(
            model_name="batch",
            name="order",
            field=models.PositiveSmallIntegerField(
                default=1, unique=True, verbose_name="ترتيب الدفع"
            ),
            preserve_default=False,
        ),
    ]
