# Generated by Django 5.0.14 on 2025-08-22 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("admin_app", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="coursestructure",
            name="structure",
        ),
        migrations.DeleteModel(
            name="CourseEnrollment",
        ),
        migrations.DeleteModel(
            name="CourseStructure",
        ),
    ]
