# Generated by Django 5.0.14 on 2025-08-22 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_app", "0003_remove_coursestructure_structure_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AcademicYear",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20, unique=True)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("is_active", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "السنة الدراسية",
                "verbose_name_plural": "السنوات الدراسية",
                "ordering": ["-start_date"],
            },
        ),
    ]
