# Generated by Django 5.2.5 on 2025-09-08 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("admin_app", "0003_university_college"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="college",
            options={
                "ordering": ["name"],
                "verbose_name": "كلية",
                "verbose_name_plural": "الكليات",
            },
        ),
        migrations.AlterModelOptions(
            name="university",
            options={
                "ordering": ["name"],
                "verbose_name": "جامعة",
                "verbose_name_plural": "الجامعات",
            },
        ),
    ]
