# Generated by Django 5.0.14 on 2025-08-09 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_app", "0003_alter_batch_options_batch_order"),
        ("authentcat_app", "0013_alter_semester_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="instructor",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="courses",
                to="authentcat_app.teacher",
                verbose_name="المعلم",
            ),
        ),
    ]
