# Generated by Django 5.2.5 on 2025-09-08 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_app", "0004_alter_college_options_alter_university_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="department",
            name="college",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="Dept_colleges",
                to="admin_app.college",
                verbose_name="الكلية",
            ),
            preserve_default=False,
        ),
    ]
