# Generated by Django 5.0.14 on 2025-08-09 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_app", "0004_alter_course_instructor"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="prerequisites",
        ),
        migrations.RemoveField(
            model_name="course",
            name="structure",
        ),
        migrations.AddField(
            model_name="coursestructure",
            name="structure",
            field=models.OneToOneField(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="course",
                to="admin_app.course",
            ),
            preserve_default=False,
        ),
    ]
