# Generated by Django 5.2.5 on 2025-09-08 13:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_app", "0005_department_college"),
    ]

    operations = [
        migrations.AlterField(
            model_name="university",
            name="email",
            field=models.EmailField(
                max_length=254,
                unique=True,
                validators=[
                    django.core.validators.EmailValidator(
                        message="صيغة البريد الإلكتروني غير صحيحة"
                    )
                ],
                verbose_name="البريد الإلكتروني",
            ),
        ),
        migrations.AlterField(
            model_name="university",
            name="name",
            field=models.CharField(
                max_length=255, unique=True, verbose_name="اسم الجامعة"
            ),
        ),
        migrations.AlterField(
            model_name="university",
            name="phone",
            field=models.CharField(
                blank=True,
                max_length=20,
                validators=[
                    django.core.validators.RegexValidator(
                        message="رقم الهاتف يجب أن يكون من 7 إلى 15 رقم ويمكن أن يبدأ بـ +",
                        regex="^\\+?\\d{7,15}$",
                    )
                ],
                verbose_name="رقم الهاتف",
            ),
        ),
        migrations.AddConstraint(
            model_name="college",
            constraint=models.UniqueConstraint(
                fields=("university", "name"), name="unique_college_per_university"
            ),
        ),
        migrations.AddConstraint(
            model_name="college",
            constraint=models.CheckConstraint(
                condition=models.Q(("name", ""), _negated=True),
                name="college_name_not_empty",
            ),
        ),
        migrations.AddConstraint(
            model_name="university",
            constraint=models.CheckConstraint(
                condition=models.Q(("name", ""), _negated=True),
                name="university_name_not_empty",
            ),
        ),
    ]
