# Generated by Django 5.0.14 on 2025-08-09 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "admin_app",
            "0005_remove_course_prerequisites_remove_course_structure_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="coursestructure",
            name="class_work_max",
            field=models.PositiveIntegerField(
                blank=True,
                default=0,
                null=True,
                verbose_name="الدرجة العظمى لأعمال الفصل",
            ),
        ),
        migrations.AlterField(
            model_name="coursestructure",
            name="midterm_exam_max",
            field=models.PositiveIntegerField(
                blank=True,
                default=0,
                null=True,
                verbose_name="الدرجة العظمى للامتحان النصفي",
            ),
        ),
    ]
