# Generated by Django 5.0.14 on 2025-08-12 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_app", "0006_alter_coursestructure_class_work_max_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="batch",
            options={
                "ordering": ["major__name", "order"],
                "verbose_name": "دفعة",
                "verbose_name_plural": "الدفعات",
            },
        ),
        migrations.AlterField(
            model_name="batch",
            name="order",
            field=models.PositiveSmallIntegerField(
                editable=False, verbose_name="ترتيب الدفعة"
            ),
        ),
        migrations.AddConstraint(
            model_name="batch",
            constraint=models.UniqueConstraint(
                fields=("major", "order"), name="unique_order_per_major"
            ),
        ),
    ]
