# Generated by Django 5.0.14 on 2025-08-12 08:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_app", "0007_alter_batch_options_alter_batch_order_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="batch",
            name="major",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="التخصص",
                to="admin_app.major",
            ),
        ),
    ]
