# Generated by Django 5.0.14 on 2025-08-17 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_app", "0008_alter_batch_major"),
    ]

    operations = [
        migrations.CreateModel(
            name="Semester",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="اسم الفصل"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="كود الفصل"
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(
                        unique=True, verbose_name="ترتيب الفصول الدراسية"
                    ),
                ),
                (
                    "level",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="semester",
                        to="admin_app.level",
                        verbose_name="المستوى",
                    ),
                ),
            ],
            options={
                "verbose_name": "فصل دراسي",
                "verbose_name_plural": "الفصول الدراسية",
                "ordering": ["order"],
            },
        ),
        migrations.AlterField(
            model_name="course",
            name="semester",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="courses",
                to="admin_app.semester",
                verbose_name="الفصل الدراسي",
            ),
        ),
        migrations.AlterField(
            model_name="courseenrollment",
            name="semester",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="enrollments",
                to="admin_app.semester",
                verbose_name="الفصل الدراسي",
            ),
        ),
    ]
