"""
Django settings for ems project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-vo%h#0t%egw==a7&et&-(vxj8xirns5-x83o9c7ixf1)4r^y^^"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []



AUTH_USER_MODEL = 'authentcat_app.User'

# إعدادات إضافية لتجاوز متطلبات الإيميل
ACCOUNT_EMAIL_REQUIRED = False  # إذا كنت تستخدم django-allauth

# Application definition

INSTALLED_APPS = [
    #the app created by developer
    'jazzmin',
    'authentcat_app.apps.AuthentcatAppConfig',
    # "admin_reorder",
    # ^ the app created by developer^^

    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    #the app created by developer
    'widget_tweaks',
    'admin_app.apps.AdminAppConfig',
    'conttroll_app.apps.ConttrollAppConfig',
    'taecher_app.apps.TaecherAppConfig',
    'core_app.apps.CoreAppConfig',
    'student_app.apps.StudentAppConfig',
    'django_currentuser',
]




MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    
    #the MIDDLEWARE created by developer
    "django_currentuser.middleware.ThreadLocalUserMiddleware"
    # "admin_reorder.middleware.ModelAdminReorder",  
    
]


# ADMIN_REORDER = [
#     {
#         'app': 'authentcat_app',
#         'models': [
#             'authentcat_app.user',
#             'authentcat_app.basicuser',
#             'authentcat_app.manager',
#             'authentcat_app.controlcommitteemember',
#             'authentcat_app.teacher',
#             'authentcat_app.student',
#             'authentcat_app.profile',
#         ]
#     },
# ]





ROOT_URLCONF = "ems.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join ( BASE_DIR , 'Templates')],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "ems.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# -----------data connect with postqreSQL-------------- 
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql',
#         'NAME': 'ems',
#         'USER': 'postgres',
#         'PASSWORD': 'm123&456m',
#         'HOST': 'localhost',  # أو عنوان الخادم
#         'PORT': '5432',      # البورت الافتراضي لـ PostgreSQL
#     }
# }


# -------------data connect with sqlserver-------------- 
DATABASES = {
    'default': {
        'ENGINE': 'mssql',
        'NAME': 'ems1',  # استبدل هذا باسم قاعدة البيانات الفعلي
        'HOST': 'DESKTOP-A33RERJ',     # كما يظهر في Server Name
        'OPTIONS': {
            'driver': 'ODBC Driver 17 for SQL Server',
            'Trusted_Connection': 'yes',
            'extra_params': 'Encrypt=no'  # إذا كنت لا تستخدم التشفير
        },
    }
}


# # -------------data connect with mysql-------------- 
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.mysql',
#         'NAME': 'ems1',
#         'USER': 'root',
#         'PASSWORD': '',  # إذا كان لديك كلمة مرور، ضعها هنا
#         'PORT': '3388',
#     }
# }



# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]






# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "ar"
# LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')  


# إعدادات الملفات الوسائط (إذا كنت تستخدم رفع ملفات من المستخدمين)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# هذا اذا كان الستاتيك في مجلد واحد فقط في مجلد المشروع اما الان في كل تطبيق الستاتيك الخاصة بة لا داعي للتحديد
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'ems/static'),  # مسار مجلد الملفات الثابتة الخاص بك
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"








# ====================== jazzmin admin panel pack===================================
# Custom Admin Settings
JAZZMIN_SETTINGS = {
    # ملفات JS مخصصة (استخدم ملف واحد فقط وادمج فيه أي كود تحتاجه)
    "custom_js":"js/sidebar-scroll.js",
    # ملف CSS مخصص
    "custom_css": "css/rtl.css",

    # العناوين والعلامات
    "site_title": "نظام الامتحانات الالكترونية",
    "site_header": "نظام الامتحانات الالكترونية",
    "site_brand": "جامعة تعز فرع التربة",
    "site_icon": "img/tize_unvercity_logo.svg",
    # "site_logo": "img/Mohammed.jpg",
    "welcome_sign": "نظام الامتحانات الالكترونية",
    "copyright": " ",

    # القوائم العلوية
    "topmenu_links": [
        # تأكد أن عندك URL باسم home في urls.py
        # أو غيّرها لمسار ثابت مثل "/admin/"
        {"name": "لوحة التحكم", "url": "/admin/", "permissions": ["auth.view_user"]},
        {"model": "auth.User"},
    ],

    # الشريط الجانبي
    "show_sidebar": True,
    "navigation_expanded": False,  # القوائم مغلقة بشكل افتراضي

    # الأيقونات
    "icons": {
        "admin.LogEntry": "fas fa-file",
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",

        "api.User": "fas fa-user",
        "api.Profile": "fas fa-address-card",
        "api.Post": "fas fa-th",
        "api.Category": "fas fa-tag",
        "api.Comment": "fas fa-envelope",
        "api.Notification": "fas fa-bell",
        "api.Bookmark": "fas fa-heart",
    },

    "default_icon_parents": "fas fa-chevron-circle-right",
    "default_icon_children": "fas fa-arrow-circle-right",

    "related_modal_active": False,
    "show_ui_builder": True,

    # نماذج
    "changeform_format": "horizontal_tabs",
    "changeform_format_overrides": {
        "auth.user": "collapsible",
        "auth.group": "vertical_tabs",
    },

    # ترتيب التطبيقات والنماذج
    "order_with_respect_to": [
        # admin_app
        "admin_app",
        "admin_app.Department",
        "admin_app.AcademicYear",
        "admin_app.Major",
        "admin_app.Level",
        "admin_app.Semester",
        "admin_app.Batch",
        "admin_app.Course",

        # authentcat_app
        "authentcat_app",
        "authentcat_app.User",
        "authentcat_app.basicuser",
        "authentcat_app.manager",
        "authentcat_app.controlcommitteemember",
        "authentcat_app.teacher",
        "authentcat_app.student",
        "authentcat_app.profile",

        # conttroll_app
        "conttroll_app",
        "conttroll_app.ExamSchedule",
        "conttroll_app.ExamHall",
        "conttroll_app.StudentExamAttendance",
        "conttroll_app.ExamStatusLog",
        "conttroll_app.CourseEnrollment",
        "conttroll_app.Grade",

        # taecher_app
        "taecher_app",
        "taecher_app.CourseStructure",
        "taecher_app.Exam",
        "taecher_app.Question",
        "taecher_app.EssayQuestion",
        "taecher_app.EssayAnswerEvaluation",
        "taecher_app.NumericQuestion",
        "taecher_app.MultipleChoiceQuestion",
        "taecher_app.TrueFalseQuestion",
        "taecher_app.Answer",

        # student_app
        "student_app",
        "student_app.StudentExamAttempt",
        "student_app.StudentEssayAnswer",
        "student_app.StudentNumericAnswer",
        "student_app.StudentTrueFalseQutionAnswer",
        "student_app.StudentMultipleChoiceQuestionAnswer",
    ],
}

# Jazzmin Tweaks

JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": True,
    "brand_small_text": False,
    "brand_colour": "navbar-indigo",
    "accent": "accent-olive",
    "navbar": "navbar-indigo navbar-dark",
    "no_navbar_border": False,
    "navbar_fixed": False,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": False,
    "sidebar": "sidebar-dark-indigo",
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": True,

    "sidebar_nav_compact_style": False,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": False,
    "theme": "default",
    "dark_mode_theme": None,
    "button_classes": {
        "primary": "btn-outline-primary",
        "secondary": "btn-outline-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success"
    }
}
# ==========================================================================================================






# إعدادات الجلسة
SESSION_ENGINE = "django.contrib.sessions.backends.db"  # يستخدم قاعدة البيانات لتخزين الجلسات
SESSION_COOKIE_AGE = 1209600  # 14 يومًا بالثواني
SESSION_EXPIRE_AT_BROWSER_CLOSE = False  # الجلسة لا تنتهي عند إغلاق المتصفح
SESSION_COOKIE_SECURE = False  # True إذا كنت تستخدم HTTPS
SESSION_COOKIE_HTTPONLY = True  # لأمان أفضل
SESSION_COOKIE_SAMESITE = 'Lax'  # لمنع بعض هجمات CSRF

