# Generated by Django 5.0.14 on 2025-08-22 07:57

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("admin_app", "0001_initial"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(
                        max_length=255,
                        unique=True,
                        validators=[
                            django.core.validators.MinLengthValidator(
                                3, message="يجب أن يكون الاسم الكامل على الأقل 3 أحرف"
                            ),
                            django.core.validators.MaxLengthValidator(
                                255, message="يجب ألا يتجاوز الاسم الكامل 255 حرفًا"
                            ),
                            django.core.validators.RegexValidator(
                                message="يجب أن يحتوي الاسم الكامل على أحرف عربية فقط",
                                regex="^[\u0600-ۿ\\s]+$",
                            ),
                        ],
                        verbose_name="الاسم الكامل",
                    ),
                ),
                (
                    "gender",
                    models.IntegerField(
                        choices=[(1, "ذكر"), (0, "أنثى")],
                        default=1,
                        verbose_name="النوع",
                    ),
                ),
                (
                    "user_type",
                    models.IntegerField(
                        choices=[(1, "أساسي"), (2, "طالب")],
                        default=2,
                        verbose_name="نوع المستخدام",
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        default="photo/defualt_img.png",
                        upload_to="photo/%Y/%m/%d",
                        verbose_name="صورة المستخدام",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الانشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التعديل"),
                ),
                (
                    "last_login",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ اخر تسجيل دخول"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="هل الحساب فعال"),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="سوف يكون لة كل الصلاحيات انتبة ",
                        verbose_name="هل الحساب سوبر لة كل الصلاحيات",
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False, verbose_name="هل الحساب من الموظفين"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_users",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المستخدام الذي انشئ",
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to.",
                        related_name="custom_user_set",
                        related_query_name="custom_user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_users",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المستخدام الذي عدل",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="custom_user_set",
                        related_query_name="custom_user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "مستخدم",
                "verbose_name_plural": "المستخدمون",
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="BasicUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "basic_user_type",
                    models.IntegerField(
                        choices=[(1, "معلم"), (2, "عضو لجنة مراقبة"), (3, "مدير")]
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        limit_choices_to={"user_type": 1},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="basicuser",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "مستخدم أساسي",
                "verbose_name_plural": "المستخدمون الأساسيون",
            },
        ),
        migrations.CreateModel(
            name="ControlCommitteeMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "basic_user",
                    models.OneToOneField(
                        limit_choices_to={"basic_user_type": 2},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="committee_member",
                        to="authentcat_app.basicuser",
                    ),
                ),
            ],
            options={
                "verbose_name": "عضو لجنة مراقبة",
                "verbose_name_plural": "أعضاء لجنة المراقبة",
            },
        ),
        migrations.CreateModel(
            name="Manager",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "basic_user",
                    models.OneToOneField(
                        limit_choices_to={"basic_user_type": 3},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="manager",
                        to="authentcat_app.basicuser",
                    ),
                ),
            ],
            options={
                "verbose_name": "مدير",
                "verbose_name_plural": "المديرون",
            },
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="البريد الإلكتروني"
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        max_length=20,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="يجب أن يبدأ رقم الهاتف اليمني بـ +967 ويتبعه 9 أرقام (للموبايل: 7/3/8/1) أو 9 أرقام للخطوط الأرضية",
                                regex="^\\+9677[1378]\\d{7}$|^\\+967\\d{9}$",
                            )
                        ],
                        verbose_name="رقم الهاتف",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="_profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المستخدم",
                    ),
                ),
            ],
            options={
                "verbose_name": "الملف الشخصي",
                "verbose_name_plural": "الملفات الشخصية",
            },
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "university_id",
                    models.CharField(
                        max_length=20,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="يجب أن يتكون الرقم الجامعي من 8 أرقام",
                                regex="^[0-9]{8}$",
                            )
                        ],
                        verbose_name="الرقم الجامعي",
                    ),
                ),
                (
                    "registration_type",
                    models.IntegerField(
                        choices=[(1, "نظام"), (2, "موازي"), (3, "نفقة خاصة")],
                        verbose_name="نوع التسجيل",
                    ),
                ),
                (
                    "Batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Batch",
                        to="admin_app.batch",
                        verbose_name="الدفعة",
                    ),
                ),
                (
                    "Major",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Major",
                        to="admin_app.major",
                        verbose_name="التخصص",
                    ),
                ),
                (
                    "Semester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Semester",
                        to="admin_app.semester",
                        verbose_name="الفصل الدراسي",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        limit_choices_to={"user_type": 2},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "طالب",
                "verbose_name_plural": "الطلاب",
            },
        ),
        migrations.CreateModel(
            name="Teacher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "basic_user",
                    models.OneToOneField(
                        limit_choices_to={"basic_user_type": 1},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teacher",
                        to="authentcat_app.basicuser",
                    ),
                ),
            ],
            options={
                "verbose_name": "معلم",
                "verbose_name_plural": "المعلمون",
            },
        ),
    ]
