# Generated by Django 5.0.14 on 2025-08-07 06:54

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentcat_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="phone_number",
            field=models.CharField(
                max_length=20,
                validators=[
                    django.core.validators.RegexValidator(
                        message="يجب أن يبدأ رقم الهاتف اليمني بـ +967 ويتبعه 9 أرقام (للموبايل: 7/3/8/1) أو 9 أرقام للخطوط الأرضية",
                        regex="^\\+9677[1378]\\d{7}$|^\\+967\\d{9}$",
                    )
                ],
                verbose_name="رقم الهاتف",
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="university_id",
            field=models.CharField(
                max_length=20,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="يجب أن يتكون الرقم الجامعي من 8 أرقام",
                        regex="^[0-9]{8}$",
                    )
                ],
                verbose_name="الرقم الجامعي",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="تاريخ الانشاء"),
        ),
        migrations.AlterField(
            model_name="user",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_users",
                to=settings.AUTH_USER_MODEL,
                verbose_name="المستخدام الذي انشئ",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="full_name",
            field=models.CharField(
                max_length=255,
                unique=True,
                validators=[
                    django.core.validators.MinLengthValidator(
                        3, message="يجب أن يكون الاسم الكامل على الأقل 3 أحرف"
                    ),
                    django.core.validators.MaxLengthValidator(
                        255, message="يجب ألا يتجاوز الاسم الكامل 255 حرفًا"
                    ),
                    django.core.validators.RegexValidator(
                        message="يجب أن يحتوي الاسم الكامل على أحرف عربية فقط",
                        regex="^[\u0600-ۿ\\s]+$",
                    ),
                ],
                verbose_name="الاسم الكامل",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="gender",
            field=models.IntegerField(
                choices=[(1, "ذكر"), (0, "أنثى")], verbose_name="النوع"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="هل الحساب فعال"),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_staff",
            field=models.BooleanField(
                default=False, verbose_name="هل الحساب من الموظفين"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_superuser",
            field=models.BooleanField(
                default=False,
                help_text="سوف يكون لة كل الصلاحيات انتبة ",
                verbose_name="هل الحساب سوبر لة كل الصلاحيات",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_login",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="تاريخ اخر تسجيل دخول"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="photo",
            field=models.ImageField(
                help_text="الرجاء إختيار صورة",
                upload_to="photo/%Y/%m/%d",
                verbose_name="صورة المستخدام",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="تاريخ التعديل"),
        ),
        migrations.AlterField(
            model_name="user",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="updated_users",
                to=settings.AUTH_USER_MODEL,
                verbose_name="المستخدام الذي عدل",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="user_type",
            field=models.IntegerField(
                choices=[(1, "أساسي"), (2, "طالب")], verbose_name="نوع المستخدام"
            ),
        ),
    ]
