# Generated by Django 5.0.14 on 2025-08-07 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentcat_app", "0002_alter_profile_phone_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="gender",
            field=models.IntegerField(
                choices=[(1, "ذكر"), (0, "أنثى")], default=1, verbose_name="النوع"
            ),
        ),
    ]
