# Generated by Django 5.0.14 on 2025-08-07 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentcat_app", "0003_alter_user_gender"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="photo",
            field=models.ImageField(
                default="photo/defualt_img.png",
                help_text="الرجاء إختيار صورة",
                upload_to="photo/%Y/%m/%d",
                verbose_name="صورة المستخدام",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="user_type",
            field=models.IntegerField(
                choices=[(1, "أساسي"), (2, "طالب")],
                default=2,
                verbose_name="نوع المستخدام",
            ),
        ),
    ]
