# Generated by Django 5.0.14 on 2025-08-07 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentcat_app", "0004_alter_user_photo_alter_user_user_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="photo",
            field=models.ImageField(
                default="photo/defualt_img.png",
                upload_to="photo/%Y/%m/%d",
                verbose_name="صورة المستخدام",
            ),
        ),
    ]
