# Generated by Django 5.0.14 on 2025-08-09 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_app", "0001_initial"),
        ("authentcat_app", "0005_alter_user_photo"),
    ]

    operations = [
        migrations.CreateModel(
            name="Semester",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="اسم الفصل"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="كود الفصل"
                    ),
                ),
                ("start_date", models.DateField(verbose_name="تاريخ البدء")),
                ("end_date", models.DateField(verbose_name="تاريخ الانتهاء")),
                (
                    "level",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="semester",
                        to="admin_app.level",
                        verbose_name="المستوى",
                    ),
                ),
            ],
            options={
                "verbose_name": "فصل دراسي",
                "verbose_name_plural": "الفصول الدراسية",
                "ordering": ["level__order"],
            },
        ),
    ]
