# Generated by Django 5.0.14 on 2025-08-09 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentcat_app", "0006_semester"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="semester",
            name="end_date",
        ),
        migrations.RemoveField(
            model_name="semester",
            name="start_date",
        ),
    ]
