# Generated by Django 5.0.14 on 2025-08-09 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_app", "0002_initial"),
        ("authentcat_app", "0007_remove_semester_end_date_remove_semester_start_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="semester",
            name="level",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="semester",
                to="admin_app.level",
                verbose_name="المستوى",
            ),
        ),
    ]
