# Generated by Django 5.0.14 on 2025-08-09 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentcat_app", "0008_alter_semester_level"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="semester",
            options={
                "ordering": ["order"],
                "verbose_name": "فصل دراسي",
                "verbose_name_plural": "الفصول الدراسية",
            },
        ),
        migrations.AddField(
            model_name="semester",
            name="order",
            field=models.PositiveSmallIntegerField(
                default=1, unique=True, verbose_name="ترتيب المستوى"
            ),
            preserve_default=False,
        ),
    ]
