# Generated by Django 5.0.14 on 2025-08-09 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentcat_app", "0009_alter_semester_options_semester_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="semester",
            name="order",
            field=models.PositiveSmallIntegerField(verbose_name="ترتيب المستوى"),
        ),
    ]
