# Generated by Django 5.0.14 on 2025-08-09 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_app", "0006_alter_coursestructure_class_work_max_and_more"),
        ("authentcat_app", "0013_alter_semester_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="Batch",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="Batch",
                to="admin_app.batch",
                verbose_name="الدفعة",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="student",
            name="Major",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="Major",
                to="admin_app.major",
                verbose_name="التخصص",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="student",
            name="Semester",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="Semester",
                to="authentcat_app.semester",
                verbose_name="الفصل الدراسي",
            ),
            preserve_default=False,
        ),
    ]
