# Generated by Django 5.0.14 on 2025-08-09 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentcat_app", "0014_student_batch_student_major_student_semester"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="expected_graduation",
        ),
    ]
