# Generated by Django 5.0.14 on 2025-08-17 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_app", "0009_semester_alter_course_semester_and_more"),
        ("authentcat_app", "0015_remove_student_expected_graduation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="Semester",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="Semester",
                to="admin_app.semester",
                verbose_name="الفصل الدراسي",
            ),
        ),
        migrations.DeleteModel(
            name="Semester",
        ),
    ]
