# Generated by Django 5.2.5 on 2025-09-05 14:51

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("admin_app", "0002_initial"),
        ("authentcat_app", "0001_initial"),
        ("student_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(verbose_name="نص السؤال")),
                (
                    "points",
                    models.PositiveIntegerField(default=0, verbose_name="درجة السؤال"),
                ),
                (
                    "question_type",
                    models.IntegerField(
                        choices=[
                            (1, "صح أو خطأ"),
                            (2, "عددي"),
                            (3, "اختيار من متعدد"),
                            (4, "مقالي"),
                        ],
                        verbose_name="نوع السؤال",
                    ),
                ),
                (
                    "files",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="question_files/",
                        verbose_name="ملفات",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_questions",
                        to="authentcat_app.basicuser",
                        verbose_name="المعلم الذي انشئ السؤال",
                    ),
                ),
            ],
            options={
                "verbose_name": "سؤال",
                "verbose_name_plural": "الأسئلة",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Exam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="اسم الامتحان"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, null=True, verbose_name="وصف الامتحان"
                    ),
                ),
                (
                    "duration",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MaxValueValidator(
                                5, "لا يمكن أن تتجاوز مدة الامتحان 5 ساعات"
                            )
                        ],
                        verbose_name="مدة الامتحان (ساعات)",
                    ),
                ),
                (
                    "exam_type",
                    models.IntegerField(
                        choices=[(1, "نصفي"), (2, "نهائي"), (3, "تجريبي")],
                        verbose_name="نوع الامتحان",
                    ),
                ),
                (
                    "exam_category",
                    models.IntegerField(
                        choices=[(1, "نموذج 1"), (2, "نموذج 2"), (3, "اضطراري")],
                        default=1,
                        verbose_name="صنف الامتحان",
                    ),
                ),
                (
                    "total_marks",
                    models.PositiveIntegerField(verbose_name="درجة الامتحان"),
                ),
                (
                    "show_results",
                    models.BooleanField(
                        default=False, verbose_name="عرض النتائج مباشرة"
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="exam_files/",
                        verbose_name="ملف الامتحان",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exams",
                        to="admin_app.course",
                        verbose_name="المقرر",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_exams",
                        to="authentcat_app.teacher",
                        verbose_name="أنشئ بواسطة",
                    ),
                ),
            ],
            options={
                "verbose_name": "امتحان",
                "verbose_name_plural": "الامتحانات",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CourseStructure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "final_exam_max",
                    models.PositiveIntegerField(
                        verbose_name="الدرجة العظمى للامتحان النهائي"
                    ),
                ),
                (
                    "midterm_exam_max",
                    models.PositiveIntegerField(
                        blank=True,
                        default=0,
                        null=True,
                        verbose_name="الدرجة العظمى للامتحان النصفي",
                    ),
                ),
                (
                    "class_work_max",
                    models.PositiveIntegerField(
                        blank=True,
                        default=0,
                        null=True,
                        verbose_name="الدرجة العظمى لأعمال الفصل",
                    ),
                ),
                (
                    "structure",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="course_structure",
                        to="admin_app.course",
                        verbose_name="المقرر",
                    ),
                ),
            ],
            options={
                "verbose_name": "هيكل المقرر",
                "verbose_name_plural": "هياكل المقررات",
            },
        ),
        migrations.CreateModel(
            name="EssayAnswerEvaluation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "awarded_marks",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="الدرجة المحتسبة",
                    ),
                ),
                (
                    "feedback",
                    models.TextField(blank=True, verbose_name="التغذية الراجعة"),
                ),
                (
                    "evaluated_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ التصحيح"
                    ),
                ),
                (
                    "is_final_evaluation",
                    models.BooleanField(default=False, verbose_name="تقييم نهائي"),
                ),
                (
                    "evaluated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="essay_evaluations",
                        to="authentcat_app.teacher",
                        verbose_name="مصحح بواسطة",
                    ),
                ),
                (
                    "student_answer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evaluations",
                        to="student_app.studentessayanswer",
                        verbose_name="إجابة الطالب",
                    ),
                ),
            ],
            options={
                "verbose_name": "تقييم إجابة مقالية",
                "verbose_name_plural": "تقييمات الإجابات المقالية",
                "ordering": ["student_answer", "-evaluated_at"],
            },
        ),
        migrations.CreateModel(
            name="EssayQuestion",
            fields=[
                (
                    "question_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="taecher_app.question",
                    ),
                ),
            ],
            options={
                "verbose_name": "سؤال مقالي",
                "verbose_name_plural": "أسئلة مقالية",
            },
            bases=("taecher_app.question",),
        ),
        migrations.CreateModel(
            name="MultipleChoiceQuestion",
            fields=[
                (
                    "question_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="taecher_app.question",
                    ),
                ),
            ],
            options={
                "verbose_name": "سؤال اختيار من متعدد",
                "verbose_name_plural": "أسئلة اختيار من متعدد",
            },
            bases=("taecher_app.question",),
        ),
        migrations.CreateModel(
            name="NumericQuestion",
            fields=[
                (
                    "question_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="taecher_app.question",
                    ),
                ),
                ("answer", models.FloatField(verbose_name="الإجابة الصحيحة")),
            ],
            options={
                "verbose_name": "سؤال عددي",
                "verbose_name_plural": "أسئلة عددية",
            },
            bases=("taecher_app.question",),
        ),
        migrations.CreateModel(
            name="TrueFalseQuestion",
            fields=[
                (
                    "question_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="taecher_app.question",
                    ),
                ),
            ],
            options={
                "verbose_name": "سؤال صح و خطأ",
                "verbose_name_plural": "أسئلة صح و خطأ",
            },
            bases=("taecher_app.question",),
        ),
        migrations.CreateModel(
            name="Answer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("answer_text", models.TextField(verbose_name="نص الإجابة")),
                (
                    "is_correct",
                    models.BooleanField(
                        default=False, verbose_name="هل الإجابة صحيحة؟"
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="taecher_app.question",
                        verbose_name="السؤال المرتبط",
                    ),
                ),
            ],
            options={
                "verbose_name": "إجابة",
                "verbose_name_plural": "الإجابات",
                "ordering": ["id"],
            },
        ),
        migrations.AddField(
            model_name="question",
            name="exam",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questions",
                to="taecher_app.exam",
                verbose_name="الامتحان",
            ),
        ),
    ]
