# Generated by Django 5.0.14 on 2025-08-10 13:41

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("admin_app", "0006_alter_coursestructure_class_work_max_and_more"),
        ("authentcat_app", "0015_remove_student_expected_graduation"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Exam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="اسم الامتحان")),
                (
                    "description",
                    models.TextField(
                        blank=True, null=True, verbose_name="وصف الامتحان"
                    ),
                ),
                (
                    "duration",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MaxValueValidator(
                                5, "لا يمكن أن تتجاوز مدة الامتحان 5 ساعات"
                            )
                        ],
                        verbose_name="مدة الامتحان (ساعات)",
                    ),
                ),
                (
                    "exam_type",
                    models.IntegerField(
                        choices=[(1, "نصفي"), (2, "نهائي"), (3, "تجريبي")],
                        verbose_name="نوع الامتحان",
                    ),
                ),
                (
                    "exam_category",
                    models.IntegerField(
                        choices=[(1, "نموذج 1"), (2, "نموذج 2"), (3, "اضطراري")],
                        default=1,
                        verbose_name="صنف الامتحان",
                    ),
                ),
                (
                    "total_marks",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="درجة الامتحان"
                    ),
                ),
                (
                    "show_results",
                    models.BooleanField(
                        default=False, verbose_name="عرض النتائج مباشرة"
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="exam_files/",
                        verbose_name="ملف الامتحان",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exams",
                        to="admin_app.course",
                        verbose_name="المقرر",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_exams",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="أنشئ بواسطة",
                    ),
                ),
            ],
            options={
                "verbose_name": "امتحان",
                "verbose_name_plural": "الامتحانات",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ExamStatusLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[
                            (1, "منشئ"),
                            (2, "مرسل للكنترول"),
                            (3, "مستلم من الكنترول"),
                            (4, "ملغي"),
                        ],
                        verbose_name="الحالة",
                    ),
                ),
                (
                    "change_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ التغيير"
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="ملاحظات"),
                ),
                (
                    "changed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="exam_status_changes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="تم التغيير بواسطة",
                    ),
                ),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_logs",
                        to="taecher_app.exam",
                        verbose_name="الامتحان",
                    ),
                ),
            ],
            options={
                "verbose_name": "سجل حالة الامتحان",
                "verbose_name_plural": "سجلات حالات الامتحانات",
                "ordering": ["-change_date"],
            },
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=255, verbose_name="عنوان السؤال"),
                ),
                ("text", models.TextField(verbose_name="نص السؤال")),
                ("points", models.PositiveIntegerField(verbose_name="درجة السؤال")),
                (
                    "question_type",
                    models.IntegerField(
                        choices=[
                            (1, "صح أو خطأ"),
                            (2, "عددي"),
                            (3, "اختيار من متعدد"),
                            (4, "مقالي"),
                        ],
                        verbose_name="نوع السؤال",
                    ),
                ),
                (
                    "files",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="question_files/",
                        verbose_name="ملفات",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="taecher_app.exam",
                        verbose_name="الامتحان",
                    ),
                ),
            ],
            options={
                "verbose_name": "سؤال",
                "verbose_name_plural": "الأسئلة",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="StudentExamAttendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "attendance_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الحضور"
                    ),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[(0, "أول مرة"), (1, "إعادة")],
                        default=0,
                        verbose_name="حالة الحضور",
                    ),
                ),
                (
                    "score",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="الدرجة"
                    ),
                ),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_attendances",
                        to="taecher_app.exam",
                        verbose_name="الامتحان",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exam_attendances",
                        to="authentcat_app.student",
                        verbose_name="الطالب",
                    ),
                ),
            ],
            options={
                "verbose_name": "حضور طالب للامتحان",
                "verbose_name_plural": "حضور الطلاب للامتحانات",
                "unique_together": {("student", "exam")},
            },
        ),
    ]
