# Generated by Django 5.0.14 on 2025-08-22 07:57

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("admin_app", "0002_initial"),
        ("authentcat_app", "0001_initial"),
        ("student_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EssayAnswerEvaluation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "awarded_marks",
                    models.PositiveIntegerField(
                        help_text="يجب أن تكون بين 0 ودرجة السؤال",
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="الدرجة المحتسبة",
                    ),
                ),
                (
                    "feedback",
                    models.TextField(blank=True, verbose_name="التغذية الراجعة"),
                ),
                (
                    "evaluated_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ التصحيح"
                    ),
                ),
                (
                    "is_final_evaluation",
                    models.BooleanField(
                        default=False,
                        help_text="هل هذا التقييم هو التقييم النهائي للإجابة؟",
                        verbose_name="تقييم نهائي",
                    ),
                ),
                (
                    "evaluated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="essay_evaluations",
                        to="authentcat_app.teacher",
                        verbose_name="مصحح بواسطة",
                    ),
                ),
                (
                    "student_answer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evaluations",
                        to="student_app.studentessayanswer",
                        verbose_name="إجابة الطالب",
                    ),
                ),
            ],
            options={
                "verbose_name": "تقييم إجابة مقالية",
                "verbose_name_plural": "تقييمات الإجابات المقالية",
                "ordering": ["student_answer", "-evaluated_at"],
            },
        ),
        migrations.CreateModel(
            name="Exam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="اسم الامتحان"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, null=True, verbose_name="وصف الامتحان"
                    ),
                ),
                (
                    "duration",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MaxValueValidator(
                                5, "لا يمكن أن تتجاوز مدة الامتحان 5 ساعات"
                            )
                        ],
                        verbose_name="مدة الامتحان (ساعات)",
                    ),
                ),
                (
                    "exam_type",
                    models.IntegerField(
                        choices=[(1, "نصفي"), (2, "نهائي"), (3, "تجريبي")],
                        verbose_name="نوع الامتحان",
                    ),
                ),
                (
                    "exam_category",
                    models.IntegerField(
                        choices=[(1, "نموذج 1"), (2, "نموذج 2"), (3, "اضطراري")],
                        default=1,
                        verbose_name="صنف الامتحان",
                    ),
                ),
                (
                    "total_marks",
                    models.PositiveIntegerField(verbose_name="درجة الامتحان"),
                ),
                (
                    "show_results",
                    models.BooleanField(
                        default=False, verbose_name="عرض النتائج مباشرة"
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="exam_files/",
                        verbose_name="ملف الامتحان",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exams",
                        to="admin_app.course",
                        verbose_name="المقرر",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_exams",
                        to="authentcat_app.teacher",
                        verbose_name="أنشئ بواسطة",
                    ),
                ),
            ],
            options={
                "verbose_name": "امتحان",
                "verbose_name_plural": "الامتحانات",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EssayQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question_text", models.TextField(verbose_name="نص السؤال")),
                (
                    "marks",
                    models.PositiveIntegerField(default=0, verbose_name="درجة السؤال"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="essay_questions",
                        to="taecher_app.exam",
                        verbose_name="الاختبار المرتبط",
                    ),
                ),
            ],
            options={
                "verbose_name": "سؤال مقالي",
                "verbose_name_plural": "أسئلة مقالية",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="NumericQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question_text", models.TextField(verbose_name="نص السؤال")),
                ("answer", models.FloatField(verbose_name="الإجابة الصحيحة")),
                (
                    "marks",
                    models.PositiveIntegerField(default=0, verbose_name="درجة السؤال"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="numeric_questions",
                        to="taecher_app.exam",
                        verbose_name="الاختبار المرتبط",
                    ),
                ),
            ],
            options={
                "verbose_name": "سؤال عددي",
                "verbose_name_plural": "أسئلة عددية",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="عنوان السؤال",
                    ),
                ),
                ("text", models.TextField(verbose_name="نص السؤال")),
                (
                    "points",
                    models.PositiveIntegerField(default=0, verbose_name="درجة السؤال"),
                ),
                (
                    "question_type",
                    models.IntegerField(
                        choices=[(1, "صح أو خطأ"), (3, "اختيار من متعدد")],
                        verbose_name="نوع السؤال",
                    ),
                ),
                (
                    "files",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="question_files/",
                        verbose_name="ملفات",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="taecher_app.exam",
                        verbose_name="الامتحان",
                    ),
                ),
            ],
            options={
                "verbose_name": "سؤال",
                "verbose_name_plural": "الأسئلة",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Answer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("answer_text", models.TextField(verbose_name="نص الإجابة")),
                (
                    "is_correct",
                    models.BooleanField(
                        default=False,
                        help_text="0 للخطأ، 1 للصحيح",
                        verbose_name="هل الإجابة صحيحة؟",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="taecher_app.question",
                        verbose_name="السؤال المرتبط",
                    ),
                ),
            ],
            options={
                "verbose_name": "إجابة",
                "verbose_name_plural": "الإجابات",
                "ordering": ["id"],
            },
        ),
    ]
