# Generated by Django 5.0.14 on 2025-08-11 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taecher_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Answer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("answer_text", models.TextField(verbose_name="نص الإجابة")),
                (
                    "is_correct",
                    models.BooleanField(
                        default=False,
                        help_text="0 للخطأ، 1 للصحيح",
                        verbose_name="هل الإجابة صحيحة؟",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="taecher_app.question",
                        verbose_name="السؤال المرتبط",
                    ),
                ),
            ],
            options={
                "verbose_name": "إجابة",
                "verbose_name_plural": "الإجابات",
                "ordering": ["id"],
            },
        ),
    ]
