# Generated by Django 5.0.14 on 2025-08-22 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_app", "0003_remove_coursestructure_structure_and_more"),
        ("taecher_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CourseStructure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "final_exam_max",
                    models.PositiveIntegerField(
                        verbose_name="الدرجة العظمى للامتحان النهائي"
                    ),
                ),
                (
                    "midterm_exam_max",
                    models.PositiveIntegerField(
                        blank=True,
                        default=0,
                        null=True,
                        verbose_name="الدرجة العظمى للامتحان النصفي",
                    ),
                ),
                (
                    "class_work_max",
                    models.PositiveIntegerField(
                        blank=True,
                        default=0,
                        null=True,
                        verbose_name="الدرجة العظمى لأعمال الفصل",
                    ),
                ),
                (
                    "structure",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="course",
                        to="admin_app.course",
                    ),
                ),
            ],
            options={
                "verbose_name": "هيكل المقرر",
                "verbose_name_plural": "هياكل المقررات",
            },
        ),
    ]
