# Generated by Django 5.0.14 on 2025-08-11 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taecher_app", "0002_answer"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="question",
            name="points",
        ),
        migrations.AddField(
            model_name="question",
            name="mark",
            field=models.PositiveIntegerField(default=0, verbose_name="درجة السؤال"),
        ),
        migrations.AlterField(
            model_name="question",
            name="title",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="عنوان السؤال"
            ),
        ),
        migrations.CreateModel(
            name="EssayQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question_text", models.TextField(verbose_name="نص السؤال")),
                (
                    "marks",
                    models.PositiveIntegerField(default=0, verbose_name="درجة السؤال"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="essay_questions",
                        to="taecher_app.exam",
                        verbose_name="الاختبار المرتبط",
                    ),
                ),
            ],
            options={
                "verbose_name": "سؤال مقالي",
                "verbose_name_plural": "أسئلة مقالية",
                "ordering": ["created_at"],
            },
        ),
    ]
