# Generated by Django 5.0.14 on 2025-08-26 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("taecher_app", "0002_coursestructure"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="question",
            name="title",
        ),
    ]
