# Generated by Django 5.0.14 on 2025-08-11 12:49

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentcat_app", "0015_remove_student_expected_graduation"),
        ("taecher_app", "0003_remove_question_points_question_mark_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentEssayAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("answer_text", models.TextField(verbose_name="إجابة الطالب")),
                (
                    "attempt_number",
                    models.PositiveIntegerField(
                        default=1,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="رقم المحاولة",
                    ),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="وقت التسليم"),
                ),
                (
                    "is_final",
                    models.BooleanField(
                        default=False,
                        help_text="هل هذه الإجابة هي النسخة النهائية المقدمة؟",
                        verbose_name="إجابة نهائية",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_answers",
                        to="taecher_app.essayquestion",
                        verbose_name="السؤال المقالي",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="essay_answers",
                        to="authentcat_app.student",
                        verbose_name="الطالب",
                    ),
                ),
            ],
            options={
                "verbose_name": "إجابة طالب مقالية",
                "verbose_name_plural": "إجابات الطلاب المقالية",
                "ordering": ["student", "question", "attempt_number"],
                "unique_together": {("question", "student", "attempt_number")},
            },
        ),
        migrations.CreateModel(
            name="EssayAnswerEvaluation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "awarded_marks",
                    models.PositiveIntegerField(
                        help_text="يجب أن تكون بين 0 ودرجة السؤال",
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="الدرجة المحتسبة",
                    ),
                ),
                (
                    "feedback",
                    models.TextField(blank=True, verbose_name="التغذية الراجعة"),
                ),
                (
                    "evaluated_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ التصحيح"
                    ),
                ),
                (
                    "is_final_evaluation",
                    models.BooleanField(
                        default=False,
                        help_text="هل هذا التقييم هو التقييم النهائي للإجابة؟",
                        verbose_name="تقييم نهائي",
                    ),
                ),
                (
                    "evaluated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="essay_evaluations",
                        to="authentcat_app.teacher",
                        verbose_name="مصحح بواسطة",
                    ),
                ),
                (
                    "student_answer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evaluations",
                        to="taecher_app.studentessayanswer",
                        verbose_name="إجابة الطالب",
                    ),
                ),
            ],
            options={
                "verbose_name": "تقييم إجابة مقالية",
                "verbose_name_plural": "تقييمات الإجابات المقالية",
                "ordering": ["student_answer", "-evaluated_at"],
            },
        ),
    ]
