# Generated by Django 5.0.14 on 2025-08-11 16:23

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taecher_app", "0004_studentessayanswer_essayanswerevaluation"),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentExamAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "attempt_number",
                    models.PositiveIntegerField(
                        default=1,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="رقم المحاولة",
                    ),
                ),
                (
                    "start_time",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="وقت بداية المحاولة"
                    ),
                ),
                (
                    "end_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="وقت نهاية المحاولة"
                    ),
                ),
                (
                    "student_notes",
                    models.TextField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="ملاحظات الطالب",
                    ),
                ),
                (
                    "objective_score",
                    models.PositiveIntegerField(
                        default=0, verbose_name="درجة الأسئلة الموضوعية"
                    ),
                ),
                (
                    "essay_score",
                    models.PositiveIntegerField(
                        default=0, verbose_name="درجة الأسئلة المقالية"
                    ),
                ),
                (
                    "total_score",
                    models.PositiveIntegerField(
                        default=0, verbose_name="الدرجة الكلية"
                    ),
                ),
                (
                    "is_submitted",
                    models.BooleanField(default=False, verbose_name="تم التسليم"),
                ),
                (
                    "attendance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempts",
                        to="taecher_app.studentexamattendance",
                        verbose_name="سجل الحضور",
                    ),
                ),
            ],
            options={
                "verbose_name": "محاولة امتحان الطالب",
                "verbose_name_plural": "محاولات امتحانات الطلاب",
                "ordering": ["attendance", "attempt_number"],
                "unique_together": {("attendance", "attempt_number")},
            },
        ),
        migrations.CreateModel(
            name="ObjectiveQuestionAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "attempt_number",
                    models.PositiveIntegerField(
                        default=1, verbose_name="رقم المحاولة للسؤال"
                    ),
                ),
                (
                    "is_correct",
                    models.BooleanField(default=False, verbose_name="الإجابة صحيحة"),
                ),
                (
                    "awarded_mark",
                    models.PositiveIntegerField(
                        default=0, verbose_name="الدرجة المحتسبة"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="وقت المحاولة"
                    ),
                ),
                (
                    "chosen_answer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="taecher_app.answer",
                        verbose_name="الإجابة المختارة",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_attempts",
                        to="taecher_app.question",
                        verbose_name="السؤال",
                    ),
                ),
                (
                    "exam_attempt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="objective_attempts",
                        to="taecher_app.studentexamattempt",
                        verbose_name="محاولة الامتحان",
                    ),
                ),
            ],
            options={
                "verbose_name": "محاولة سؤال موضوعي",
                "verbose_name_plural": "محاولات الأسئلة الموضوعية",
                "ordering": ["exam_attempt", "question", "attempt_number"],
                "unique_together": {("exam_attempt", "question", "attempt_number")},
            },
        ),
    ]
