# Generated by Django 5.0.14 on 2025-08-11 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentcat_app", "0015_remove_student_expected_graduation"),
        ("taecher_app", "0005_studentexamattempt_objectivequestionattempt"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exam",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_exams",
                to="authentcat_app.teacher",
                verbose_name="أنشئ بواسطة",
            ),
        ),
    ]
