# Generated by Django 5.0.14 on 2025-08-11 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taecher_app", "0006_alter_exam_created_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exam",
            name="name",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="اسم الامتحان"
            ),
        ),
    ]
