# Generated by Django 5.0.14 on 2025-08-11 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("taecher_app", "0007_alter_exam_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="question",
            old_name="mark",
            new_name="points",
        ),
    ]
