# Generated by Django 5.0.14 on 2025-08-11 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taecher_app", "0008_rename_mark_question_points"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exam",
            name="total_marks",
            field=models.PositiveIntegerField(
                default=100, verbose_name="درجة الامتحان"
            ),
            preserve_default=False,
        ),
    ]
