# Generated by Django 5.0.14 on 2025-08-12 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taecher_app", "0009_alter_exam_total_marks"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="objectivequestionattempt",
            options={
                "ordering": ["question", "attempt_number"],
                "verbose_name": "محاولة سؤال موضوعي",
                "verbose_name_plural": "محاولات الأسئلة الموضوعية",
            },
        ),
        migrations.AlterField(
            model_name="objectivequestionattempt",
            name="attempt_number",
            field=models.PositiveIntegerField(
                default=1, editable=False, verbose_name="رقم المحاولة للسؤال"
            ),
        ),
    ]
