# Generated by Django 5.0.14 on 2025-08-12 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taecher_app", "0010_alter_objectivequestionattempt_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="objectivequestionattempt",
            name="awarded_mark",
            field=models.PositiveIntegerField(
                default=0, editable=False, verbose_name="الدرجة المحتسبة"
            ),
        ),
        migrations.AlterField(
            model_name="objectivequestionattempt",
            name="is_correct",
            field=models.BooleanField(
                default=False, editable=False, verbose_name="الإجابة صحيحة"
            ),
        ),
    ]
