# Generated by Django 5.0.14 on 2025-08-15 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taecher_app", "0011_alter_objectivequestionattempt_awarded_mark_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentessayanswer",
            name="attempt_number",
            field=models.PositiveIntegerField(
                default=1, editable=False, verbose_name="رقم المحاولة"
            ),
        ),
    ]
