# Generated by Django 5.0.14 on 2025-08-15 14:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taecher_app", "0012_alter_studentessayanswer_attempt_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentexamattempt",
            name="attempt_number",
            field=models.PositiveIntegerField(
                default=1,
                editable=False,
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="رقم المحاولة",
            ),
        ),
    ]
