# Generated by Django 5.0.14 on 2025-08-15 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("taecher_app", "0013_alter_studentexamattempt_attempt_number"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="studentexamattempt",
            unique_together=set(),
        ),
    ]
