# Generated by Django 5.0.14 on 2025-08-15 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("taecher_app", "0014_alter_studentexamattempt_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="studentexamattempt",
            unique_together={("attendance", "attempt_number")},
        ),
    ]
