# Generated by Django 5.0.14 on 2025-08-15 21:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taecher_app", "0015_alter_studentexamattempt_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentessayanswer",
            name="exam_attempt",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="essay_attempts",
                to="taecher_app.studentexamattempt",
                verbose_name="محاولة الامتحان",
            ),
        ),
    ]
