# Generated by Django 5.0.14 on 2025-08-15 21:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taecher_app", "0016_studentessayanswer_exam_attempt"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentessayanswer",
            name="exam_attempt",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="essay_attempts",
                to="taecher_app.studentexamattempt",
                verbose_name="محاولة الامتحان",
            ),
            preserve_default=False,
        ),
    ]
