# Generated by Django 5.0.14 on 2025-08-15 22:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentcat_app", "0015_remove_student_expected_graduation"),
        ("taecher_app", "0017_alter_studentessayanswer_exam_attempt"),
    ]

    operations = [
        migrations.CreateModel(
            name="NumericQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question_text", models.TextField(verbose_name="نص السؤال")),
                ("answer", models.FloatField(verbose_name="الإجابة الصحيحة")),
                (
                    "marks",
                    models.PositiveIntegerField(default=0, verbose_name="درجة السؤال"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="numeric_questions",
                        to="taecher_app.exam",
                        verbose_name="الاختبار المرتبط",
                    ),
                ),
            ],
            options={
                "verbose_name": "سؤال عددي",
                "verbose_name_plural": "أسئلة عددية",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="StudentNumericAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "student_answer",
                    models.FloatField(verbose_name="إجابة الطالب الرقمية"),
                ),
                (
                    "obtained_mark",
                    models.FloatField(
                        default=0, editable=False, verbose_name="الدرجة المستحقة"
                    ),
                ),
                (
                    "attempt_number",
                    models.PositiveIntegerField(
                        default=1, editable=False, verbose_name="رقم المحاولة"
                    ),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="وقت التسليم"),
                ),
                (
                    "is_final",
                    models.BooleanField(
                        default=False,
                        help_text="هل هذه الإجابة هي النسخة النهائية المقدمة؟",
                        verbose_name="إجابة نهائية",
                    ),
                ),
                (
                    "exam_attempt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="numeric_attempts",
                        to="taecher_app.studentexamattempt",
                        verbose_name="محاولة الامتحان",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_answers",
                        to="taecher_app.numericquestion",
                        verbose_name="السؤال العددي",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="numeric_answers",
                        to="authentcat_app.student",
                        verbose_name="الطالب",
                    ),
                ),
            ],
            options={
                "verbose_name": "إجابة طالب عددية",
                "verbose_name_plural": "إجابات الطلاب العددية",
                "ordering": ["student", "question", "attempt_number"],
                "unique_together": {("question", "student", "attempt_number")},
            },
        ),
    ]
