# Generated by Django 5.0.14 on 2025-08-15 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taecher_app", "0018_numericquestion_studentnumericanswer"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentexamattempt",
            name="numeric_score",
            field=models.PositiveIntegerField(
                default=0, verbose_name="درجة الأسئلة العددية"
            ),
        ),
    ]
