# Generated by Django 5.0.14 on 2025-08-16 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("taecher_app", "0019_studentexamattempt_numeric_score"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="studentessayanswer",
            options={
                "ordering": ["question", "attempt_number"],
                "verbose_name": "إجابة طالب مقالية",
                "verbose_name_plural": "إجابات الطلاب المقالية",
            },
        ),
        migrations.AlterModelOptions(
            name="studentnumericanswer",
            options={
                "ordering": ["question", "attempt_number"],
                "verbose_name": "إجابة طالب عددية",
                "verbose_name_plural": "إجابات الطلاب العددية",
            },
        ),
        migrations.AlterUniqueTogether(
            name="studentessayanswer",
            unique_together={("question", "attempt_number")},
        ),
        migrations.AlterUniqueTogether(
            name="studentnumericanswer",
            unique_together={("question", "attempt_number")},
        ),
        migrations.RemoveField(
            model_name="studentessayanswer",
            name="student",
        ),
        migrations.RemoveField(
            model_name="studentnumericanswer",
            name="student",
        ),
    ]
