# Generated by Django 5.0.14 on 2025-08-16 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taecher_app", "0020_alter_studentessayanswer_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="question_type",
            field=models.IntegerField(
                choices=[(1, "صح أو خطأ"), (3, "اختيار من متعدد")],
                verbose_name="نوع السؤال",
            ),
        ),
    ]
