# Generated by Django 5.0.14 on 2025-08-22 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("conttroll_app", "0002_initial"),
        ("student_app", "0001_initial"),
        ("taecher_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="objectivequestionattempt",
            name="chosen_answer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="taecher_app.answer",
                verbose_name="الإجابة المختارة",
            ),
        ),
        migrations.AddField(
            model_name="objectivequestionattempt",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="student_attempts",
                to="taecher_app.question",
                verbose_name="السؤال",
            ),
        ),
        migrations.AddField(
            model_name="studentessayanswer",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="student_answers",
                to="taecher_app.essayquestion",
                verbose_name="السؤال المقالي",
            ),
        ),
        migrations.AddField(
            model_name="studentexamattempt",
            name="attendance",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attempts",
                to="conttroll_app.studentexamattendance",
                verbose_name="سجل الحضور",
            ),
        ),
        migrations.AddField(
            model_name="studentessayanswer",
            name="exam_attempt",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="essay_attempts",
                to="student_app.studentexamattempt",
                verbose_name="محاولة الامتحان",
            ),
        ),
        migrations.AddField(
            model_name="objectivequestionattempt",
            name="exam_attempt",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="objective_attempts",
                to="student_app.studentexamattempt",
                verbose_name="محاولة الامتحان",
            ),
        ),
        migrations.AddField(
            model_name="studentnumericanswer",
            name="exam_attempt",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="numeric_attempts",
                to="student_app.studentexamattempt",
                verbose_name="محاولة الامتحان",
            ),
        ),
        migrations.AddField(
            model_name="studentnumericanswer",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="student_answers",
                to="taecher_app.numericquestion",
                verbose_name="السؤال العددي",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="studentexamattempt",
            unique_together={("attendance", "attempt_number")},
        ),
        migrations.AlterUniqueTogether(
            name="studentessayanswer",
            unique_together={("question", "attempt_number")},
        ),
        migrations.AlterUniqueTogether(
            name="objectivequestionattempt",
            unique_together={("exam_attempt", "question", "attempt_number")},
        ),
        migrations.AlterUniqueTogether(
            name="studentnumericanswer",
            unique_together={("question", "attempt_number")},
        ),
    ]
